### ISSUE TITLE
What is a status of this project ?

### ISSUE THREAD

**Issue by tsibelman** [awr/KafkaClient#28]
I see that this repository is not updated in a long time, can you tell us how far this client from production quality ?

**Comment by awr** [comment]
It's been stalled recently since I needed to get the infrastructure setup (Kafka / Zookeeper / etc) before coming back to leverage this. It took me down a bit of a rabbit hole at work into some serious devops work, which I am just at the tail end of.

That being said, I'm likely to be back on this project within a couple weeks fairly aggressively. There are a few key missing pieces in my mind before this is truly production ready:
- SASL support
- lz4 of snappy support fully working

There are some fixes that still need to take place (make some of the tests a bit more robust, verifying telemetry, ssl, backoffs work in concert across the client, etc). I'd also like to see a commandline tool for operational support in reading off a topic, but that should be fairly straightforward.

My plan is to use this in production, and I had hoped to be doing so already -- other things have unfortunately taken priority up until recently.

**Comment by tsibelman** [comment]
Thank you, so if we like to try your code and don't need SASL an compression support it should reasnably work already ?

**Comment by awr** [comment]
Yeah -- and am happy to work through issues with you if you find them. Like I said, I am planning on taking this to production in the near term on my side, so I'm going to need to tackle anything you uncover anyways.
